### ISSUE TITLE
Puma v6.5.0 not started

### ISSUE THREAD

**Issue by galinski** [kigster/puma-daemon#29]
With the same config as for Puma 6.4.3, Puma 6.5.0 + puma-daemon 0.3.2 not started in production enviroment.

The error simply said:
```
wrong number of arguments (given 1, expected 0)
```

when I comment out:

```ruby
#require 'puma/daemon'
#daemonize true
```

in puma config file, it started without any problems.

Puma 6.5.0 works well in dev enviroment and also in prod without `puma-daemon`.

I checked Puma's changelog, but I don't see any possible break changes other than a slight change to `threads`, but backwards compatible.

**Comment by kigster** [comment]
Thanks for the report! Seems like it should be a pretty quick fix.

**Comment by kigster** [comment]
Work in progress — a PR with failing specs is here:

https://github.com/kigster/puma-daemon/pull/30

**Comment by kigster** [comment]
@galinski Are you in a position to test a potential fix?

Get puma-daemon with:

```
git clone -b kig/puma-6.5.0 https://github.com/kigster/puma-daemon
```

See if you can start it against this branch. Thanks!
